#Development creds & keys
development:
  DEV_ENV: true
  tHE_CITY_SECRET: 'YOUR DEVELOPMENT CITY SECRET'
  THE_CITY_APP_ID: 'YOUR DEVELOPMENT CITY APP ID'

  TWILIO_ACCOUNT: 'YOUR TWILIO ACCOUNT'
  TWILIO_TOKENID: 'YOUR TWILIO TOKENID'
  TWILIO_FROM_NUMBER: 'YOUR TWILIO PHONE NUMBER'

  CITY_ADMIN_SECRET: 'YOUR CITY ADMIN SECRET'
  CITY_USER_TOKEN: 'YOUR CITY USER TOKEN'

  SMTP_USER: 'YOUR SMTP USER NAME'
  SMTP_PASSWORD: 'YOUR SMTP PASSWORD'
  SMTP_DOMAIN: 'YOUR SMTP DOMAIN'
  SMTP_ADDRESS: 'YOUR SMTP SERVER ADDRESS'
  SMTP_FROM: 'FROM EMAIL'
  SMTP_PORT: 587 #SMTP PORT, CHANGE AS NEEDED
  SMTP_TLS: true #Change as needed

production:
  DEV_ENV: true
  THE_CITY_SECRET: 'YOUR PRODUCTION CITY SECRET'
  THE_CITY_APP_ID: 'YOUR PRODUCTION CITY APP ID'

  TWILIO_ACCOUNT: 'YOUR TWILIO ACCOUNT'
  TWILIO_TOKENID: 'YOUR TWILIO TOKENID'
  TWILIO_FROM_NUMBER: 'YOUR TWILIO PHONE NUMBER'

  CITY_ADMIN_SECRET: 'YOUR CITY ADMIN SECRET'
  CITY_USER_TOKEN: 'YOUR CITY USER TOKEN'

  SMTP_USER: 'YOUR SMTP USER NAME'
  SMTP_PASSWORD: 'YOUR SMTP PASSWORD'
  SMTP_DOMAIN: 'YOUR SMTP DOMAIN'
  SMTP_ADDRESS: 'YOUR SMTP SERVER ADDRESS'
  SMTP_FROM: 'FROM EMAIL'
  SMTP_PORT: 587 #SMTP PORT, CHANGE AS NEEDED
  SMTP_TLS: true #Change as needed