#development:
#  adapter: sqlite3
#  encoding: unicode
#  database: db/city-texting-dev
#  pool: 5


development:
  adapter: postgresql
  encoding: unicode
  database: city-texting-public-testing
  pool: 5
  host: localhost
  username: rails
  password: rails
  min-messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: city-texting-public-testing
  pool: 5
  host: localhost
  username: rails
  password: rails
  min-messages: warning